services:
  telegram-bot-responser:
    image: ghcr.io/dom6770/telegram-bot-responser
    container_name:  telegram-bot-responser

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/usr/src/app/data

networks:
  telegram-bot-responser:
    name: telegram-bot-responser